/* 
 * This file is part of the RTBServer distribution (https://github.com/yoori/rtbserver).
 * RTBServer is DSP server that allow to bid (see RTB auction) targeted ad
 * via RTB protocols (OpenRTB, Google AdExchange, Yandex RTB)
 *
 * Copyright (c) 2014 Yuri Kuznecov <yuri.kuznecov@gmail.com>.
 * 
 * This program is free software: you can redistribute it and/or modify  
 * it under the terms of the GNU General Public License as published by  
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef USERINFOSVCS_USERBINDCONTROLLER_IDL_
#define USERINFOSVCS_USERBINDCONTROLLER_IDL_

#include <CORBACommons/ProcessControl.idl>
#include <UserInfoSvcs/UserBindServer/UserBindServer.idl>

module AdServer
{
  module UserInfoSvcs
  {
    valuetype UserBindMapperValueType supports UserBindMapper
    {
      private boolean non_empty_;
    };

    struct UserBindDescription
    {
      UserBindServer user_bind_server;
      UserBindServer::ChunkIdSeq chunk_ids;
    };

    typedef sequence<UserBindDescription>
      UserBindDescriptionSeq;

    /*
    interface _TAO_BUG
    {
      CORBACommons::AProcessControl::ALIVE_STATUS get_alive_type();

      string
      comment();
    };
    */

    interface UserBindClusterControl: CORBACommons::IProcessControl
    {};

    /**
     *  UserBindController
     */
    interface UserBindController
    {
      exception NotReady {};

      exception ImplementationException
      {
        string description;
      };

      UserBindDescriptionSeq
      get_session_description()
        raises(ImplementationException, NotReady);
    };
  }; // module UserInfoSvcs
}; // module AdServer

#endif // USERINFOSVCS_USERBINDCONTROLLER_IDL_
