/* 
 * This file is part of the RTBServer distribution (https://github.com/yoori/rtbserver).
 * RTBServer is DSP server that allow to bid (see RTB auction) targeted ad
 * via RTB protocols (OpenRTB, Google AdExchange, Yandex RTB)
 *
 * Copyright (c) 2014 Yuri Kuznecov <yuri.kuznecov@gmail.com>.
 * 
 * This program is free software: you can redistribute it and/or modify  
 * it under the terms of the GNU General Public License as published by  
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _USER_INFO_SVCS_USER_INFO_MANAGER_CONTROLLER_IDL_
#define _USER_INFO_SVCS_USER_INFO_MANAGER_CONTROLLER_IDL_

#include <UserInfoSvcs/UserInfoManager/UserInfoManager.idl>
#include <UserInfoSvcs/UserInfoManager/UserInfoManagerControl.idl>

module AdServer
{
  module UserInfoSvcs
  {
    struct UserInfoManagerDescription
    {
      UserInfoManager user_info_manager;
      ChunkIdSeq chunk_ids;
    };
    
    typedef
      sequence<UserInfoManagerDescription>
      UserInfoManagerDescriptionSeq;

    /**
     *  UserInfoManagerSession
     *  interface for matching user id
     */
    valuetype UserInfoManagerSession supports UserInfoMatcher
    {
      private UserInfoManagerDescriptionSeq user_info_managers;
    };

    /**
     *  UserInfoManagerController
     */
    interface UserInfoManagerController
    {
      exception NotReady {};
      
      exception ImplementationException
      {
        string description;
      };

      UserInfoManagerSession get_session()
        raises(ImplementationException, NotReady);

      void get_session_description(
        out UserInfoManagerDescriptionSeq session_description)
        raises(ImplementationException, NotReady);
      
    };

  }; // module UserInfoSvcs
  
}; // module AdServer

#endif // _USER_INFO_SVCS_USER_INFO_MANAGER_CONTROLLER_IDL_
